---
title: Dynamic Population Mapping (Smartpop) - Part 7
author: Damien C. Jacques
date: '2018-10-28'
slug: dynamic-population-mapping-smartpop-part-7
categories:
  - R
summary: This Notebook details the steps of the data analysis performed in the frame of the Smartpop project -- Dynamic Population WP (part 7).
tags:
  - population
  - mobile phone data
  - statistics
header:
  caption: ''
  image: ''
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE,
                      eval = T )
```

```{r, echo = F, eval = F}
library(data.table)
db.new <- fread("/media/ubuntu/DATA/Data/Smartpop/FinalDB/FinalDB_085km2.csv")
area <- fread("/media/ubuntu/DATA/Data/Smartpop/Zone/area_085_inKm2.csv")  

Mat_BE <- dcast(ID_Grid ~  DATE_HOUR, 
                data = db.new, 
                value.var = "NBR_SIM_BE")
Mat_BE <- as.matrix(Mat_BE)[, -1]
colnames(Mat_BE) <- rep(1:365, each = 24)[-7971]

column.names <- c(73:(24*7), rep(1:(24*7), 51), 1:96)
column.names <- column.names[-7971]
colnames(Mat_BE) <- column.names

Week <- as.data.frame( # sapply returns a list here, so we convert it to a data.frame
    sapply(unique(colnames(Mat_BE)), # for each unique column name
       function(col) rowMeans(Mat_BE[,colnames(Mat_BE) == col]) # calculate row means
    )
  )

Mat_BE_copy <- as.matrix(Mat_BE)
Mat_BE_copy <- Mat_BE_copy - as.matrix(Week[, as.numeric(colnames(Mat_BE_copy))]) 

# compute trend
library(foreach)
library(doMC)
registerDoMC(8)

x <- 1:ncol(Mat_BE_copy)
trend <- foreach(i = 1:nrow(Mat_BE_copy), .combine = rbind) %dopar% {
  z <- predict(loess(as.numeric(Mat_BE_copy[i,]) ~ x, span = 0.1, degree = 2))
  z  #return value for the iterations
}

remainder <- as.matrix(Mat_BE_copy) - trend
remainder <- as.matrix(remainder) + abs(min(as.matrix(remainder)))
Mat_BE <- Mat_BE - remainder
Mat_BE <- Mat_BE[, colnames(Mat_BE) %in% seq(22, 168, 24)]

PopWorkingDays_WE <- Mat_BE

for (i in 1:ncol(PopWorkingDays_WE)) {
  predData <- exp(3.140073 + 0.8176294 * log(Mat_BE[, i]))
  PopWorkingDays_WE[, i] <- predData * 9893623/sum(predData * area$`area(km2)`)
}

save(PopWorkingDays_WE, file = "/media/ubuntu/DATA/Data/Smartpop/Population/pop_year_rawData9pm.Rda")
```

```{r, echo = F, eval =F}
library(sf)

load("/media/ubuntu/DATA/Data/Smartpop/Dates/Dates_vec.Rda")
load("/media/ubuntu/DATA/Data/Smartpop/Population/pop_year_rawData9pm.Rda")
PopWorkingDays_WE <- scrime::rowScales(PopWorkingDays_WE)
colnames(PopWorkingDays_WE) <- 1:365

shp <- st_read("/media/ubuntu/DATA/Data/Smartpop/Zone/zone_50m_0.85km2_dissolve.shp", quiet = T)
st_crs(shp) <- "+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013
+y_0=5400088.438 +ellps=intl +units=m +no_defs"

shp <- cbind(shp, PopWorkingDays_WE)

# quantization breaks of the rate
bks <- c(0, 1,2,3,4, 5, 10, 20)
# get a color palette
cols <- c('#f2f0f7','#dadaeb','#bcbddc','#9e9ac8','#807dba','#6a51a3','#4a1486')
  
for (i in 1:365)  {
  png(paste0("/media/ubuntu/DATA/Data/Smartpop/Map/UnusualPop/UnusualPop_",i, ".png"), width = 800, height = 654)
  par(mar = c(0,0,1.5,0))
  choroLayer(x = shp, var = names(shp)[i + 1], breaks = bks, col = cols,
               border = "khaki", lwd = 0.001, 
               legend.title.txt = "", 
               legend.pos = 'bottomleft', legend.values.rnd = 0)
  layoutLayer(title = paste0("Unusual high population density ", dates[i], " (z-score)"), 
                sources = "", north = TRUE, 
                scale = 50, tabtitle = TRUE,
                frame = T,  
                author = "*model based on mobile phone data")
  dev.off()
}
```

```{r, eval = F, echo = F}
df$WE <- "week"
df$WE[df$week == 6] <- "saturday"
df$WE[df$week == 7] <- "sunday"
df$col[c(62:123,179:185,235:248,289:297, 340:353, 1:4,29:32,38:40,192:195)] <- "holidays"
df$col[df$week %in% c(6,7)] <- "WE"
```

## Extreme events

```{r, fig.width = 12, fig.height = 10}
library(ggplot2)
library(data.table)

load("/media/ubuntu/DATA/Data/Smartpop/Matrix/remainder_085km2.Rda")
load("/media/ubuntu/DATA/Data/Smartpop/Dates/Dates_vec.Rda")

db.new <- fread("/media/ubuntu/DATA/Data/Smartpop/FinalDB/FinalDB_085km2.csv")
Mat_BE <- dcast(ID_Grid ~  DATE_HOUR, 
                data = db.new, 
                value.var = "NBR_SIM_BE")
Mat_BE <- as.matrix(Mat_BE)[, -1]

df <- data.frame(date = apply(expand.grid(dates, c("00","01","02","03","04","05","06",
                                                   "07","08","09","10","11","12",
                                                   "13","14","15","16","17","18",
                                                   "19","20","21","22","23")), 1, 
                              paste, collapse = " ")[order(apply(expand.grid(dates, 
                                                 c("00","01","02","03","04","05","06",
                                                   "07","08","09","10","11","12",
                                                   "13","14","15","16","17","18",
                                                   "19","20","21","22","23")), 
                                                                 1, paste, collapse = ""))][-8760], 
                 remainder_mean = colSums(scrime::rowScales(remainder) > 5),
                 stringsAsFactors = F)

df$Date <- substr(df$date, 1,10)
df$Hour <- substr(df$date, 12,13)


library(ggplot2)

temperature <- c('#000000','#52170b','#a51b0b','#ff0000','#ff7f00','#ffc200','#ffff00','#ffff7a','#ffffbf','#ffffff')

g <- list()

start <- c(1,122,244)
end <- c(121,243,365)

for (i in 1:3) {
  g[[i]] <- ggplot(data =  df[which(df$Date %in% 
                                      as.character(dates[start[i]:end[i]])),], 
               aes(y = Hour, x = Date)) + 
    geom_raster(aes(fill = log10(remainder_mean))) +
    scale_fill_gradientn(colours = temperature,
                         name = "Number of places\nwith unusually very\nhigh activity",
                          breaks=c(0:3), 
                      labels=c("0","1e1", "1e2", "1e3")) +
    theme(
      plot.background = element_blank(),
      panel.grid.minor = element_blank(),
      panel.grid.major = element_blank(),
      panel.background = element_blank(),
      panel.border = element_blank(),
      axis.text.x = element_text(angle = 90)) 
}

library(Rmisc)
multiplot(g[[1]], g[[2]], g[[3]])
```
```{r}
library(sf)
library(cartography)

shp <- st_read("/media/ubuntu/DATA/Data/Smartpop/Zone/zone_50m_0.85km2_dissolve.shp", quiet = T)
st_crs(shp) <- "+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013
+y_0=5400088.438 +ellps=intl +units=m +no_defs"

extreme <- rowSums(scrime::rowScales(remainder) > 5)
shp <- cbind(shp, extreme)

bks <- seq(0, 100, 20)

colors <- c('#edf8fb','#b3cde3','#8c96c6','#810f7c','#4d004b')

par(mar = c(0,0,1.5,0))
choroLayer(x = shp, var = "extreme", breaks = bks, col = colors,
             border = "khaki", lwd = 0.001, 
             legend.title.txt = "", 
             legend.pos = 'bottomleft', legend.values.rnd = 0)
layoutLayer(title = "Number of hours with unusually very high activity", 
              sources = "", north = TRUE, 
              scale = 50, tabtitle = TRUE,
              frame = T,  
              author = "*model based on mobile phone data")

```
```{r}
library(leaflet)
library(widgetframe)

shp_latlon <- st_transform(shp, crs = 4326)

pal <- colorNumeric(colors, bks)

l <- leaflet(shp_latlon) %>%
  setView(lng = 5.578661, lat = 50.633766, zoom = 12) %>%
  # Base groups
  addProviderTiles(providers$Stamen.Toner, group = "Toner") %>%
  addTiles(group = "OSM (default)") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "ESRI World Imagery") %>%
  # Overlay groups
  addPolygons(group = "show map", 
              fillColor = ~pal( extreme), color = ~pal( extreme),
              weight = 0.5, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.5,
              highlightOptions = highlightOptions(color = "white", weight = 2,
              bringToFront = TRUE)) %>%
  # Layers control
  addLayersControl(
    baseGroups = c("OSM (default)", "Toner", "ESRI World Imagery"),
    overlayGroups = c("show map"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  addLegend("bottomright", pal = pal, values = ~extreme,
    title = "Number of hours<br>with unusually very<br>high activity",
    opacity = 1)

frameWidget(l)
```

