---
title: Estimating Moments of a Mixture Distribution
author: Damien C. Jacques
date: '2018-04-10'
slug: estimating-moments-of-a-mixture-distribution
categories:
  - R
tags:
  - statistics
---



This notebook aims to visually explore the statistical meaning behind the *data fusion* proposed in [Pokhriyal, 2017](http://www.pnas.org/content/114/46/E9783).

## First example

First, we generate some gaussian distributions.

```{r}
Gaussian.1.mean <- 40
Gaussian.2.mean <- 60
Gaussian.1.sd <- 10
Gaussian.2.sd <- 10
x <- seq(-50,150,length=1000)

Gaussian.1 <- dnorm(x, mean = Gaussian.1.mean, sd = Gaussian.1.sd)
Gaussian.2 <- dnorm(x, mean = Gaussian.2.mean, sd = Gaussian.2.sd)

plot(x, Gaussian.1, col=2, type="l", ylab="Density", xlab = "", lwd=2)
lines(x, Gaussian.2, col=3, lwd=2)
legend("toprigh", bty="n", col=2:3, c("Gaussian 1", "Gaussian 2"), lty=1, lwd=2)
```

We now combine both gaussians following the procedure described in [Pokhriyal, 2017](http://www.pnas.org/content/114/46/E9783).

```{r}
weight.1 = (1/Gaussian.1.sd^2)/((1/Gaussian.1.sd^2)+(1/Gaussian.2.sd^2))
weight.2 = (1/Gaussian.2.sd^2)/((1/Gaussian.1.sd^2)+(1/Gaussian.2.sd^2))
weight.1
weight.2

Combined.mean <- weight.1*Gaussian.1.mean + weight.2*Gaussian.2.mean
Combined.sd <- sqrt(weight.1*Gaussian.1.sd^2 + weight.2*Gaussian.2.sd^2 + weight.1*weight.2*(Gaussian.1.mean-Gaussian.2.mean)^2) 


Gaussian.combined <- dnorm(x, mean = Combined.mean, sd = Combined.sd)

plot(x, Gaussian.1, col=2, type="l",  xlab = "", ylab="Density", lwd=2)
lines(x, Gaussian.2, col=3, lwd=2)
lines(x, Gaussian.combined, col=1, lwd=2)
legend("toprigh", bty="n", col=c(2,3,1), c("Gaussian 1", "Gaussian 2", "Gaussian comb."), lty=1, lwd=2)
```


## Particular cases


```{r}

Gaussian.1.mean <- 40
Gaussian.2.mean <- 60

for (sd in seq(10,30,10)){
  Gaussian.1.sd <- sd
  Gaussian.2.sd <- sd
  Gaussian.1 <- dnorm(x, mean = Gaussian.1.mean, sd = Gaussian.1.sd)
  Gaussian.2 <- dnorm(x, mean = Gaussian.2.mean, sd = Gaussian.2.sd)
  
  
  weight.1 = (1/Gaussian.1.sd^2)/((1/Gaussian.1.sd^2)+(1/Gaussian.2.sd^2))
  weight.2 = (1/Gaussian.2.sd^2)/((1/Gaussian.1.sd^2)+(1/Gaussian.2.sd^2))
  weight.1
  weight.2
  
  Combined.mean <- weight.1*Gaussian.1.mean + weight.2*Gaussian.2.mean
  Combined.sd <- sqrt(weight.1*Gaussian.1.sd^2 + weight.2*Gaussian.2.sd^2 + weight.1*weight.2*(Gaussian.1.mean-Gaussian.2.mean)^2) 
  
  
  Gaussian.combined <- dnorm(x, mean = Combined.mean, sd = Combined.sd)
  
  plot(x, Gaussian.1, col=2, type="l",  xlab = "", ylab="Density", lwd=2, main=paste0("G1 mean= 40, G2 mean=60, sd=",sd))
  lines(x, Gaussian.2, col=3, lwd=2)
  lines(x, Gaussian.combined, col=1, lwd=2)
  legend("toprigh", bty="n", col=c(2,3,1), c("Gaussian 1", "Gaussian 2", "Gaussian comb."), lty=1, lwd=2)
}
```

```{r}
Gaussian.1.sd <- 10
Gaussian.2.sd <- 10
  
for (i in seq(10,30,10)){
  Gaussian.1.mean <- 50 - i
  Gaussian.2.mean <- 50 + i

  Gaussian.1 <- dnorm(x, mean = Gaussian.1.mean, sd = Gaussian.1.sd)
  Gaussian.2 <- dnorm(x, mean = Gaussian.2.mean, sd = Gaussian.2.sd)
  
  
  weight.1 = (1/Gaussian.1.sd^2)/((1/Gaussian.1.sd^2)+(1/Gaussian.2.sd^2))
  weight.2 = (1/Gaussian.2.sd^2)/((1/Gaussian.1.sd^2)+(1/Gaussian.2.sd^2))
  weight.1
  weight.2
  
  Combined.mean <- weight.1*Gaussian.1.mean + weight.2*Gaussian.2.mean
  Combined.sd <- sqrt(weight.1*Gaussian.1.sd^2 + weight.2*Gaussian.2.sd^2 + weight.1*weight.2*(Gaussian.1.mean-Gaussian.2.mean)^2) 
  
  
  Gaussian.combined <- dnorm(x, mean = Combined.mean, sd = Combined.sd)
  
  plot(x, Gaussian.1, type="l", col=2,  xlab = "", ylab="Density", lwd=2, main=paste0("G1 mean=",50-i, ", G2 mean=",50+i, ", sd=10"))
  lines(x, Gaussian.2, col=3, lwd=2)
  lines(x, Gaussian.combined, col=1, lwd=2)
  legend("toprigh", bty="n", col=c(2,3,1), c("Gaussian 1", "Gaussian 2", "Gaussian comb."), lty=1, lwd=2)
}
```

```{r}
Gaussian.1.mean <- 40
Gaussian.2.mean <- 60
  
for (i in seq(0,15,5)){
  Gaussian.1.sd <- 20 - i
  Gaussian.2.sd <- 20 + i

  Gaussian.1 <- dnorm(x, mean = Gaussian.1.mean, sd = Gaussian.1.sd)
  Gaussian.2 <- dnorm(x, mean = Gaussian.2.mean, sd = Gaussian.2.sd)
  
  
  weight.1 = (1/Gaussian.1.sd^2)/((1/Gaussian.1.sd^2)+(1/Gaussian.2.sd^2))
  weight.2 = (1/Gaussian.2.sd^2)/((1/Gaussian.1.sd^2)+(1/Gaussian.2.sd^2))

  Combined.mean <- weight.1*Gaussian.1.mean + weight.2*Gaussian.2.mean
  Combined.sd <- sqrt(weight.1*Gaussian.1.sd^2 + weight.2*Gaussian.2.sd^2 + weight.1*weight.2*(Gaussian.1.mean-Gaussian.2.mean)^2) 
  
  
  Gaussian.combined <- dnorm(x, mean = Combined.mean, sd = Combined.sd)
  
  plot(x, Gaussian.1, col=2, type="l",  xlab = "", ylab="Density", lwd=2, main=paste0("G1 mean=",Gaussian.1.mean, ", G2 mean=",Gaussian.2.mean, ", G1 sd=",Gaussian.1.sd,", G2 sd=",Gaussian.2.sd ))
  lines(x, Gaussian.2, col=3, lwd=2)
  lines(x, Gaussian.combined, col=1, lwd=2)
  legend("toprigh", bty="n", col=c(2,3,1), c("Gaussian 1", "Gaussian 2", "Gaussian comb."), lty=1, lwd=2)
  legend("topleft", paste0("combined sd ", round(Combined.sd,2)), bty="n")
}
```
```{r}
Gaussian.1.mean <- 50
Gaussian.2.mean <- 50 

Gaussian.1.sd <- 10
Gaussian.2.sd <- 20

Gaussian.1 <- dnorm(x, mean = Gaussian.1.mean, sd = Gaussian.1.sd)
Gaussian.2 <- dnorm(x, mean = Gaussian.2.mean, sd = Gaussian.2.sd)

weight.1 = (1/Gaussian.1.sd^2)/((1/Gaussian.1.sd^2)+(1/Gaussian.2.sd^2))
weight.2 = (1/Gaussian.2.sd^2)/((1/Gaussian.1.sd^2)+(1/Gaussian.2.sd^2))


Combined.mean <- weight.1*Gaussian.1.mean + weight.2*Gaussian.2.mean
Combined.sd <- sqrt(weight.1*Gaussian.1.sd^2 + weight.2*Gaussian.2.sd^2 + weight.1*weight.2*(Gaussian.1.mean-Gaussian.2.mean)^2) 


Gaussian.combined <- dnorm(x, mean = Combined.mean, sd = Combined.sd)

plot(x, Gaussian.1, col=2, type="l",  xlab = "", ylab="Density", lwd=2, main=paste0("G1 mean=",Gaussian.1.mean, ", G2 mean=",Gaussian.2.mean, ", G1 sd=",Gaussian.1.sd,", G2 sd=",Gaussian.2.sd ))
lines(x, Gaussian.2, col=3, lwd=2)
lines(x, Gaussian.combined, col=1, lwd=2)
legend("toprigh", bty="n", col=c(2,3,1), c("Gaussian 1", "Gaussian 2", "Gaussian comb."), lty=1, lwd=2)
legend("topleft", paste0("combined sd ", round(Combined.sd,2)), bty="n")
```